name: Run AppImage

on: [push]  # 触发条件，这里设置为每次push到仓库时执行

jobs:
  build:
    runs-on: ubuntu-latest  # 运行在最新的Ubuntu Linux环境中

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出仓库代码

    - name: TEST
      run: |
        pwd
        cd /
        ls
        cd ~
        ls