name: Run AppImage

on: [push]  # 触发条件，这里设置为每次push到仓库时执行

jobs:
  build:
    runs-on: ubuntu-latest  # 运行在最新的Ubuntu Linux环境中

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出仓库代码

    - name: Install FUSE
      run: |
        sudo apt-get update
        sudo apt-get install -y fuse

    - name: Download AppImage
      run: |
        wget https://github.com/Snapmaker/OrcaSlicer/releases/download/nightlybuild/Snapmaker_Orca_Engine_Linux_V0.0.1.AppImage -O appimage.AppImage  # 下载AppImage
        chmod 777 appimage.AppImage  # 给AppImage执行权限

    - name: Copy Config
      run: |
        mkdir -p ~/.config/Snapmaker_Orca
        cp Snapmaker_Orca.conf ~/.config/Snapmaker_Orca/Snapmaker_Orca.conf
        cp Snapmaker_Orca.conf.bak ~/.config/Snapmaker_Orca/Snapmaker_Orca.conf.bak

    - name: Run AppImage
      run: |
        ./appimage.AppImage /home/runner/work/Snapmaker_Engine/Snapmaker_Engine/3DBenchy.3mf
