name: Run AppImage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache APT packages and lists
      uses: actions/cache@v2
      with:
        path: | 
          /var/cache/apt
          /var/lib/apt/lists
        key: ${{ runner.os }}-apt-${{ hashFiles('apt-dependencies.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Check and Install GUI Dependency
      run: |
        if ! dpkg -l | grep -qw libgl1-mesa-glx; then
          echo "start install dependencies"
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-glx \
            libglu1-mesa \
            libx11-6 \
            libxext6 \
            libxrender1 \
            libxi6 \
            libxtst6 \
            libxt6 \
            libxfixes3 \
            libxrandr2 \
            libasound2 \
            libpango1.0-0 \
            libatk1.0-0 \
            libgtk-3-0 \
            libgstreamer1.0-0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            libfuse-dev \
            libegl1 \
            libwebkit2gtk-4.0-37 \
            xvfb \
            at-spi2-core \
            dbus-x11 \
            imagemagick \
            locales

    - name: Cache locale configurations
      uses: actions/cache@v2
      with:
        path: /usr/lib/locale
        key: ${{ runner.os }}-locale-${{ hashFiles('locale-dependencies.txt') }}
        restore-keys: |
          ${{ runner.os }}-locale-

    - name: configure locales
      run: |
        if ! locale -a | grep -qw en_GB.UTF-8; then
          echo "start setting locales!"
          sudo locale-gen en_GB.UTF-8
          sudo dpkg-reconfigure locales

    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 10